# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e69ac9814d93a0066a50bb8dc7ba986fa1a66b411a443853bdb06f9ea72cd69f5aa3a1a5501d2aacec7f8e0eab06e16227fbdf39da05ae4e6e0c7cec1afb236a

test:
  secret_key_base: 70f7a944df893c92c7bee9c1b01893445148ea92ecda17713559a21cb9031c3dbf6dfe5da1ebffefe76759fcf6785156a61df9a7d6fa11898c69c51f49c2269d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
